export const COMPANY_LOADING_REQUEST = 'COMPANY_LOADING_REQUEST';
export const COMPANY_LOADING_SUCCESS = 'COMPANY_LOADING_SUCCESS';
export const COMPANY_LOADING_FAIL = 'COMPANY_LOADING_FAIL';
export const COMPANY_RESET = 'COMPANY_RESET';