export const COMPANY_TO_LIST_LOADING_REQUEST = 'COMPANY_TO_LIST_LOADING_REQUEST';
export const COMPANY_TO_LIST_LOADING_SUCCESS = 'COMPANY_TO_LIST_LOADING_SUCCESS';
export const COMPANY_TO_LIST_LOADING_FAIL = 'COMPANY_TO_LIST_LOADING_FAIL';