export const COMPANIES_LOADING_REQUEST = 'COMPANIES_LOADING_REQUEST';
export const COMPANIES_LOADING_SUCCESS = 'COMPANIES_LOADING_SUCCESS';
export const COMPANIES_LOADING_FAIL = 'COMPANIES_LOADING_FAIL';