export const LISTS_LOADING_REQUEST = 'LISTS_LOADING_REQUEST';
export const LISTS_LOADING_SUCCESS = 'LISTS_LOADING_SUCCESS';
export const LISTS_LOADING_FAIL = 'LISTS_LOADING_FAIL';
export const LISTS_CLEAR = 'LISTS_CLEAR';
