export const LIST_MODAL_OPEN = 'LIST_MODAL_OPEN';
export const LIST_MODAL_CLOSE = 'LIST_MODAL_CLOSE';
export const LIST_MODAL_LOADING_REQUEST = 'LIST_MODAL_LOADING_REQUEST';
export const LIST_MODAL_LOADING_SUCCESS = 'LIST_MODAL_LOADING_SUCCESS';
export const LIST_MODAL_LOADING_FAIL = 'LIST_MODAL_LOADING_FAIL';