export const LOGIN_LOADING_REQUEST = 'LOGIN_LOADING_REQUEST';
export const LOGIN_LOADING_SUCCESS = 'LOGIN_LOADING_SUCCESS';
export const LOGIN_LOADING_FAIL = 'LOGIN_LOADING_FAIL';
export const LOGOUT = 'LOGOUT';