export const NEW_LIST_MODAL_OPEN = 'NEW_LIST_MODAL_OPEN';
export const NEW_LIST_MODAL_CLOSE = 'NEW_LIST_MODAL_CLOSE';
export const NEW_LIST_MODAL_LOADING_REQUEST = 'NEW_LIST_MODAL_LOADING_REQUEST';
export const NEW_LIST_MODAL_LOADING_SUCCESS = 'NEW_LIST_MODAL_LOADING_SUCCESS';
export const NEW_LIST_MODAL_LOADING_FAIL = 'NEW_LIST_MODAL_LOADING_FAIL';