export const REGISTER_LOADING_REQUEST = 'REGISTER_LOADING_REQUEST';
export const REGISTER_LOADING_SUCCESS = 'REGISTER_LOADING_SUCCESS';
export const REGISTER_LOADING_FAIL = 'REGISTER_LOADING_FAIL';

export const REGISTER_PASSWORDS_NO_MATCH = 'REGISTER_PASSWORDS_NO_MATCH';
export const REGISTER_PASSWORDS_NO_MATCH_MESSAGE = 'Confirm password does not match password.';