export const UPDATE_LIST_LOADING_REQUEST = 'UPDATE_LIST_LOADING_REQUEST';
export const UPDATE_LIST_LOADING_SUCCESS = 'UPDATE_LIST_LOADING_SUCCESS;
export const UPDATE_LIST_LOADING_FAIL = 'UPDATE_LIST_LOADING_FAIL';